backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: img


collections:
  - label: "Index Page"
    name: "Index Page"
    files:
      - label: "Banner 1 "
        name: "Banner1 "
        file: "content/one.md"
        fields:
          - {label: Image1, name: Banner1, widget: image}
          - {label: Image2, name: Banner2, widget: image}
          - {label: Image3, name: Banner3, widget: image}