backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: img


collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/one.md"
        fields:
          - {label: Banner1, name: Banner1, widget: image}
          - {label: Banner2, name: Banner2, widget: image}
          - {label: Banner3, name: Banner3, widget: image}